#!/bin/sh
source GW_IIC_FUNC      
      
echo 3 60 > $IO_SELECT    
if [ $# -eq 0 ]; then
 echo  $FUNC_TYPE_OFFSET $AUD_SLOWER > $IO_VALUE
else
 echo $FUNC_TYPE_OFFSET $AUD_SLW_VAL > $IO_VALUE 
 echo $SET_ARGS_OFFSET 1 > $IO_VALUE
 arg=$(ten_2_hex $1) 
 echo $SET_ARGS_OFFSET $arg > $IO_VALUE
fi
 echo $FUNC_TYPE_OFFSET $IIC_STATMNT_FIN > $IO_VALUE