#!/bin/sh
# script to echo back the command followed by executing the command
# Usage: cc <command> <up to 8 command parameters separated by spaces>
# Returns: <command>:response
printf "$1": 
printf "$1 " > cc_tmp_file
if [ "$2" != 0 ] ; then
printf "$2 " >> cc_tmp_file
fi
if [ "$3" != 0 ] ; then
printf "$3 " >> cc_tmp_file
fi
if [ "$4" != 0 ] ; then
printf "$4 " >> cc_tmp_file
fi
if [ "$5" != 0 ] ; then
printf "$5 " >> cc_tmp_file
fi
if [ "$6" != 0 ] ; then
printf "$6 " >> cc_tmp_file
fi
if [ "$7" != 0 ] ; then
printf "$7 " >> cc_tmp_file
fi
if [ "$8" != 0 ] ; then
printf "$8 " >> cc_tmp_file
fi
if [ "$9" != 0 ] ; then
printf "$9 " >> cc_tmp_file
fi
chmod a+x cc_tmp_file
./cc_tmp_file
printf "\x0a"
rm -f cc_tmp_file