#!/bin/sh
source GW_IIC_FUNC

echo 3 60 > $IO_SELECT
echo $CEC_READ_ACK 0x1 > $I_RANGE
arg=$(cat $IO_VALUE  | tail -n 1 |awk '{print $2}')
arg=$(hex_2_ten  $arg)
if [ $arg -eq $CEC_SUCESS_ACK ]; then
 echo ACK
else
 echo NACK
fi