#!/bin/sh
source GW_IIC_FUNC

if [ $# -eq 0 ]; then
 return;
fi

echo 3 60 > $IO_SELECT

echo $FUNC_TYPE_OFFSET $CEC_WATCH > $IO_VALUE
echo $SET_ARGS_OFFSET 0x01 > $IO_VALUE

echo $SET_ARGS_OFFSET $1 > $IO_VALUE

echo $FUNC_TYPE_OFFSET $IIC_STATMNT_FIN > $IO_VALUE