#!/bin/sh
source GW_IIC_FUNC

echo 3 60 > $IO_SELECT

if [ $(CEC_BUS_STATE) -eq 1 ]; then  
	echo BUSY
	return;
fi

echo $FUNC_TYPE_OFFSET $CEC_TV_ON > $IO_VALUE


echo $FUNC_TYPE_OFFSET $IIC_STATMNT_FIN > $IO_VALUE