#!/bin/sh
module="1500_i2s"
device="i2s"
mode="777"

#insmod usbip_common_mod.ko 2>/dev/null
insmod ./$module.ko $* || exit 1

rm -f /dev/${device}

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`
mknod /dev/${device} c $major 0
