#!/bin/sh
module="access"
device="access"
mode="777"

/sbin/insmod ./$module.ko $* || exit 1

rm -f /dev/${device}

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`
mknod /dev/${device} c $major 0
