#!/bin/bash
# Last Modified 2017-10-17 - Just Add Power
echo 4 4000 > /sys/devices/platform/i2c/bus_init
echo 4 60 > /sys/devices/platform/i2c/io_select
echo b6 1 > /sys/devices/platform/i2c/i_range
TILER=$(cat /sys/devices/platform/i2c/io_value | tail -n 1 | awk '{print $2}')
if [ -z $TILER ];then
	echo 0
else
	echo 1
fi
